sound_recognition:
  ros__parameters:
    core: sound_recognition
    afferent: audio_input
    audio_input:
      topics:
        [
          "/audio",
          "/audio/channel0",
          "/audio/channel1",
          "/audio/channel2",
          "/audio/channel3",
          "/audio/channel4",
          "/audio/channel5",
          "/doa",
          "/sed",
        ]
      types:
        [
          "audio_common_msgs/msg/AudioData",
          "audio_common_msgs/msg/AudioData",
          "audio_common_msgs/msg/AudioData",
          "audio_common_msgs/msg/AudioData",
          "audio_common_msgs/msg/AudioData",
          "audio_common_msgs/msg/AudioData",
          "audio_common_msgs/msg/AudioData",
          "geometry_msgs/msg/PoseStamped",
          "sound_msgs/msg/SoundEventDetection",
        ]
    efferent: audio_output
    audio_output:
      topics: ["/sound_detections"]
      types: ["sound_msgs/msg/SoundDetection"]
    meta: meta
    coupling: coupling
