sound_recognition:
  ros__parameters:
    core: sound_recognition
    afferent: audio_input
    audio_input:
      topics:
        [
          "/audio",
          "/audio/channel0",
          "/audio/channel1",
          "/audio/channel2",
          "/audio/channel3",
          "/audio/channel4",
          "/audio/channel5",
          "/doa",
          "/doa_raw",
          "/vad",
          "/speech_audio",
        ]
      types:
        [
          "audio_common_msgs/msg/AudioData",
          "audio_common_msgs/msg/AudioData",
          "audio_common_msgs/msg/AudioData",
          "audio_common_msgs/msg/AudioData",
          "audio_common_msgs/msg/AudioData",
          "audio_common_msgs/msg/AudioData",
          "audio_common_msgs/msg/AudioData",
          "geometry_msgs/msg/PoseStamped",
          "std_msgs/msg/Int32",
          "std_msgs/msg/Bool",
          "audio_common_msgs/msg/AudioData",
        ]
    efferent: audio_output
    audio_output:
      topics: ["/sound_detections"]
      types: ["sound_msgs/msg/SoundDetection"]
    meta: default_meta
    coupling: default_coupling
